import assert from 'node:assert/strict';
import test from 'node:test';
import { UpstreamError, isModelResult, parseModelJson } from './provider.js';

/** What the model is now asked for: a transcription and LaTeX, nothing else. */
const VALID = {
  originalText: 'Some text',
  formulas: [{ latex: 'E = mc^2' }],
};

test('parses a clean JSON reply', async () => {
  const result = await parseModelJson(JSON.stringify(VALID), 'Test');
  assert.equal(result.originalText, 'Some text');
  assert.equal(result.formulas.length, 1);
});

test('recovers JSON from a markdown code fence', async () => {
  // Local models wrap the object in ```json despite the schema being enforced.
  const raw = '```json\n' + JSON.stringify(VALID) + '\n```';
  assert.equal((await parseModelJson(raw, 'Test')).formulas.length, 1);
});

test('recovers JSON from an unlabelled code fence', async () => {
  const raw = '```\n' + JSON.stringify(VALID) + '\n```';
  assert.equal((await parseModelJson(raw, 'Test')).formulas.length, 1);
});

test('recovers JSON wrapped in prose', async () => {
  const raw = `Here is the extracted data:\n${JSON.stringify(VALID)}\nLet me know if you need more.`;
  assert.equal((await parseModelJson(raw, 'Test')).originalText, 'Some text');
});

test('normalizes unicode maths in the recovered latex', async () => {
  const raw = JSON.stringify({ originalText: '', formulas: [{ latex: 'x = ±√2' }] });
  const result = await parseModelJson(raw, 'Test');
  assert.equal(result.formulas[0].latex, 'x = \\pm \\sqrt{2}');
});

test('derives mathml and speech from the latex', async () => {
  // The model supplies none of these; they are generated by rule, so the four
  // representations of one formula cannot disagree.
  const raw = JSON.stringify({ originalText: '', formulas: [{ latex: '\\frac{1}{2}' }] });
  const [formula] = (await parseModelJson(raw, 'Test')).formulas;

  assert.match(formula.mathml, /^<math/);
  assert.equal(formula.description, 'one half');
  assert.match(formula.mathspeak, /\S/);
  assert.equal(formula.needsReview, false);
});

test('flags a formula whose latex will not convert', async () => {
  // Narrating temml's error markup to a blind reader is worse than saying a
  // human needs to look at this one.
  const raw = JSON.stringify({ originalText: '', formulas: [{ latex: '\\frac{1}' }] });
  const [formula] = (await parseModelJson(raw, 'Test')).formulas;

  assert.equal(formula.needsReview, true);
  assert.equal(formula.mathml, '');
  assert.equal(formula.description, '');
  assert.equal(formula.latex, '\\frac{1}', 'the latex is kept so a reviewer can fix it');
});

test('ignores description and mathml if a model volunteers them', async () => {
  const raw = JSON.stringify({
    originalText: '',
    formulas: [{ latex: '\\frac{1}{2}', description: 'a half, invented', mathml: '<math>lies</math>' }],
  });
  const [formula] = (await parseModelJson(raw, 'Test')).formulas;

  assert.equal(formula.description, 'one half');
  assert.doesNotMatch(formula.mathml, /lies/);
});

test('rejects empty output', async () => {
  await assert.rejects(parseModelJson('', 'Test'), (error: UpstreamError) => {
    assert.equal(error.status, 502);
    assert.match(error.message, /returned no content/);
    return true;
  });
  await assert.rejects(parseModelJson(undefined, 'Test'), /returned no content/);
  await assert.rejects(parseModelJson('   ', 'Test'), /returned no content/);
});

test('rejects unparseable output', async () => {
  await assert.rejects(parseModelJson('I could not read the image.', 'Test'), /unexpected shape/);
});

test('rejects JSON of the wrong shape', async () => {
  await assert.rejects(parseModelJson('{"foo":1}', 'Test'), /unexpected shape/);
  await assert.rejects(
    parseModelJson('{"originalText":"x","formulas":"not an array"}', 'Test'),
    /unexpected shape/,
  );
  await assert.rejects(
    parseModelJson('{"originalText":"x","formulas":[{"mathml":"<math/>"}]}', 'Test'),
    /unexpected shape/,
    'a formula missing latex must be rejected',
  );
});

test('names the provider in the error so logs say which backend failed', async () => {
  await assert.rejects(parseModelJson('nonsense', 'Ollama'), /^UpstreamError: Ollama/);
});

test('isModelResult guards each field', () => {
  assert.equal(isModelResult(VALID), true);
  assert.equal(isModelResult(null), false);
  assert.equal(isModelResult('string'), false);
  assert.equal(isModelResult({ originalText: 1, formulas: [] }), false);
  assert.equal(isModelResult({ originalText: '', formulas: [{}] }), false);
  assert.equal(isModelResult({ originalText: '', formulas: [] }), true);
});
