/** Pure LaTeX text helpers. No DOM or Angular dependencies, so they can be tested directly. */
import { splitInlineMath } from './inline-math.js';
import { normalizeLatex, unicodeToTextLatex } from './shared/latex-normalize.js';
import type { ContentBlock } from './shared/remediation.types.js';

const LATEX_ESCAPES: Record<string, string> = {
  '\\': '\\textbackslash{}',
  '&': '\\&',
  '%': '\\%',
  $: '\\$',
  '#': '\\#',
  _: '\\_',
  '{': '\\{',
  '}': '\\}',
  '~': '\\textasciitilde{}',
  '^': '\\textasciicircum{}',
};

/** Delimiter pairs the model routinely wraps its LaTeX in. Longest first. */
const MATH_DELIMITERS: ReadonlyArray<readonly [string, string]> = [
  ['\\[', '\\]'],
  ['\\(', '\\)'],
  ['$$', '$$'],
  ['$', '$'],
];

const MATH_ENVIRONMENT =
  /^\\begin\{(equation|align|alignat|gather|multline|eqnarray|flalign|array|cases|split)\*?\}/;

/**
 * Escapes text for use in a LaTeX document body.
 *
 * Escaping is a single pass: chained replaces would re-escape the braces that
 * `\textbackslash{}` and `\textasciitilde{}` introduce.
 *
 * Mathematical Unicode is then converted to commands, because transcriptions
 * routinely contain `√`, `→` and `Δ`, and `inputenc` has no definition for
 * them — pdflatex aborts on the first one. That step runs last so the
 * backslashes and dollars it introduces are not escaped in turn.
 */
export function escapeLatex(text: string): string {
  const escaped = text.replace(/[\\&%$#_{}~^]/g, (char) => LATEX_ESCAPES[char]);
  return unicodeToTextLatex(escaped);
}

/**
 * Wraps a formula in display math, tolerating the delimiters the model adds on
 * its own. Nesting `$$…$$` or an `align` environment inside `\[…\]` fails to
 * compile, so peel the former and pass the latter through bare.
 *
 * Unicode maths is normalized here as well as on the server. The server pass is
 * the one that shapes what the UI displays; this one guarantees the exported
 * document compiles even if a formula reaches the export without it. The
 * conversion is idempotent, so running it twice is harmless.
 */
export function toDisplayMath(latex: string): string {
  let body = normalizeLatex(latex.trim());

  for (const [open, close] of MATH_DELIMITERS) {
    if (body.length > open.length + close.length && body.startsWith(open) && body.endsWith(close)) {
      body = body.slice(open.length, body.length - close.length).trim();
      break;
    }
  }

  return MATH_ENVIRONMENT.test(body) ? body : `\\[\n${body}\n\\]`;
}

/** Filename the .tex export expects for the rendered image of page `index`. */
export function pageImageFilename(index: number): string {
  return `page-${index + 1}.png`;
}

/**
 * Escapes transcribed text that may hold inline `$...$` maths.
 *
 * `escapeLatex` on the whole string would turn each `$` into `\$` and print
 * the maths as source. Only the prose is escaped; each maths span is kept as
 * maths, with its Unicode normalized like any other formula.
 */
export function textWithInlineMath(text: string): string {
  return splitInlineMath(text)
    .map((segment) => {
      if (segment.kind === 'text') return escapeLatex(segment.text);
      return segment.display ? `\n${toDisplayMath(segment.latex)}\n` : `$${normalizeLatex(segment.latex)}$`;
    })
    .join('');
}

export interface LatexDocumentInput {
  blocks: readonly ContentBlock[];
  /** Pages rendered from the upload; each gets a figure. 0 for pasted LaTeX. */
  pageCount: number;
}

/**
 * The whole `.tex` export: page figures, then the content in reading order.
 *
 * Text blocks are paragraphs with their inline maths kept as maths; each maths
 * block is display maths. Formulas whose LaTeX would not convert are marked,
 * since they may not compile either and a reviewer needs to find them.
 */
export function buildLatexDocument({ blocks, pageCount }: LatexDocumentInput): string {
  const header = String.raw`\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage{amsmath}
\usepackage{graphicx}
\usepackage{geometry}
\geometry{a4paper, margin=1in}
\title{Remediated Document}
\author{Generated by Formula Accessibility Remediator}
\date{\today}

\begin{document}
\maketitle
`;

  // One figure per page. Filenames match what "Download page images" saves.
  const figures = Array.from({ length: pageCount }, (_, index) => {
    const name = pageImageFilename(index);
    return String.raw`\begin{figure}[h!]
\centering
\IfFileExists{${name}}{\includegraphics[width=\textwidth,height=\textheight,keepaspectratio]{${name}}}{\fbox{Missing ${name}}}
\caption{Original document page ${index + 1}.}
\end{figure}`;
  });
  const imageSection = pageCount
    ? `\\section*{Original Page Images}\n${figures.join('\n')}\n\\clearpage\n`
    : '';

  let formulaNumber = 0;
  const content = blocks.map((block) => {
    if (block.kind === 'text') return textWithInlineMath(block.text);
    formulaNumber++;
    const flag = block.formula.needsReview
      ? `% Formula ${formulaNumber} needs review: its LaTeX did not convert to MathML.\n`
      : '';
    return `${flag}${toDisplayMath(block.formula.latex)}`;
  });
  const contentSection = content.length ? `\\section*{Content}\n${content.join('\n\n')}\n` : '';

  return `${header}${imageSection}${contentSection}\n\\end{document}\n`;
}
